import { sha256 } from "js-sha256";

export const guestsList = [
  { invitado: "familia zaleta gonzalez", adultos: 2, niños: null },
  { invitado: "familia zaleta cordova", adultos: 3, niños: 1 },
  { invitado: "familia lazaro zaleta", adultos: 5, niños: null },
  { invitado: "familia zaleta hernandez", adultos: 5, niños: null },
  { invitado: "familia gonzalez torres", adultos: 5, niños: null },
  { invitado: "familia gonzalez segovia", adultos: 3, niños: 1 },
  { invitado: "familia sanchez garcia", adultos: 4, niños: 1 },
  { invitado: "familia sanchez aguilar", adultos: 4, niños: 1 },
  { invitado: "familia sanchez de la cruz", adultos: 2, niños: 2 },
  { invitado: "maria lopez ibarra", adultos: 2, niños: null },
  { invitado: "familia padron rodriguez", adultos: 4, niños: null },
  { invitado: "familia rodriguez martinez", adultos: 2, niños: 1 },
  { invitado: "malena rodriguez martinez", adultos: 3, niños: null },
  { invitado: "familia diaz martinez", adultos: 2, niños: null },
  { invitado: "chela sanchez delgado", adultos: 1, niños: null },
  { invitado: "elsa sanchez delgado", adultos: 2, niños: null },
  { invitado: "familia sanchez garcia", adultos: 3, niños: null },
  { invitado: "familia obregon labias", adultos: 3, niños: null },
  { invitado: "jorge obregon labias ", adultos: 1, niños: null },
  { invitado: "familia obregon sosa", adultos: 2, niños: 2 },
  { invitado: "familia espinoza caballero", adultos: 2, niños: null },
  { invitado: "familia chable falcon", adultos: 2, niños: 1 },
  { invitado: "zoila montejo", adultos: 2, niños: null },
  { invitado: "familia padilla sanchez", adultos: 3, niños: 1 },
  { invitado: "nadala carrera gil", adultos: 2, niños: null },
  { invitado: "miriam meneses", adultos: 1, niños: null },
  { invitado: "martha romero", adultos: 1, niños: null },
  { invitado: "martha morales", adultos: 1, niños: null },
  { invitado: "jairo jimenez", adultos: 2, niños: null },
  { invitado: "sra. Luz ", adultos: 3, niños: null },
  { invitado: "javier segura saviñon", adultos: 2, niños: null },
  { invitado: "famila garcia hernandez", adultos: 2, niños: null },
  { invitado: "familia de la cruz velueta", adultos: 2, niños: null },
  { invitado: "familia noverola gonzalez ", adultos: 4, niños: null },
  { invitado: "familia garcia gomez ", adultos: 2, niños: null },
  { invitado: "familia robles morales", adultos: 4, niños: null },
  { invitado: "familia ruiz robles", adultos: 2, niños: 2 },
  { invitado: "familia esquivel arias ", adultos: 3, niños: null },
  { invitado: "familia esquivel palacios", adultos: 2, niños: null },
  { invitado: "farid esquivel", adultos: 2, niños: null },
  { invitado: "ivan esquivel", adultos: 2, niños: null },
  { invitado: "familia morales fonseca", adultos: 2, niños: null },
  { invitado: "merlyn fuentes", adultos: 1, niños: null },
  { invitado: "josafhat padilla", adultos: 2, niños: null },
  { invitado: "miguel cornelio", adultos: 1, niños: null },
  { invitado: "rossely flota", adultos: 1, niños: null },
  { invitado: "jesus cornelio ", adultos: 2, niños: null },
  { invitado: "gabriel castellanos", adultos: 1, niños: null },
  { invitado: "orlando oliva", adultos: 2, niños: null },
  { invitado: "familia cruz aguilar", adultos: 2, niños: null },
  { invitado: "familia cordova sala", adultos: 2, niños: null },
  { invitado: "familia vazquez cordova", adultos: 3, niños: 1 },
  { invitado: "diego y cristian ", adultos: 2, niños: null },
  { invitado: "familia mijangos perez", adultos: 2, niños: null },
  { invitado: "fabiola torres", adultos: 2, niños: null },
  { invitado: "familia rivera torres", adultos: 3, niños: 1 },
  { invitado: "karol escamilla", adultos: 2, niños: null },
  { invitado: "nayeli ramirez", adultos: 2, niños: null },
  { invitado: "familia damas castellanos", adultos: 2, niños: null },
  { invitado: "familia martinez del cueto", adultos: 2, niños: null },
  { invitado: "familia Marin leon", adultos: 2, niños: null },
  { invitado: "familia gonzalez zurita", adultos: 2, niños: null },
  { invitado: "familia ramirez gonzalez", adultos: 2, niños: null },
  { invitado: "familia ramos lopez", adultos: 2, niños: null },
  { invitado: "laura rios", adultos: 2, niños: null },
  { invitado: "maria del carmen rodriguez", adultos: 1, niños: null },
  { invitado: "veronica gomez vargas", adultos: 2, niños: null },
  { invitado: "dora maria de la cruz ", adultos: 2, niños: null },
  { invitado: "paola", adultos: 1, niños: null },
  { invitado: "dulce", adultos: 1, niños: null },
  { invitado: "darwin romero", adultos: 1, niños: null },
  { invitado: "  ", adultos: 2, niños: null },
].map((value) => ({ ...value, id: sha256(value.invitado).slice(0, 6) }));

// let obo = JSON.stringify(
//   guestsListRaw.map((value) => ({
//     ...value,
//     niños: value.niños ? value.niños : 0,
//   }))
// );
// console.log(obo);
